
<div class="row content">
    <div class="col-sm-3 sidenav hidden-xs">
        <h2>Nome da Loja</h2>
        <div class="card">
            <img src="" alt=""/>
            <div class="container">
                <h4>Regular</h4>
                <p>Os clientes não estão muito satisfeitos...</p>
            </div>
        </div>
    </div>
    <br/>
    <div class="col-sm-9">
       <div class="row">
           <div class="col-sm-12">
               <h4>Visitas Mês</h4>
            <div id="chart_div"></div>
           </div>

       </div>
    </div>
</div>
<script src="/assets/js/loader.js"></script>
<script src="/assets/js/visitas.js"></script>